### ISSUE TITLE
Negative Numbers Prompt Error

### ISSUE THREAD

**Issue by Jonathanace** [coolkingsingh97/Leetcode-Tree-Visualizer-Public#2]
Inputting "-10,9,20,,,15,7" prompts the response "Please match the requested format."  while "10,9,20,,,15,7" does not. Similarly, "10,9,20,,,15,-7" prompts the same error, while "10,9,20,,,15,7", again, does not.

**Comment by coolkingsingh97** [comment]
This should be fixed, please let me know if otherwise.

**Comment by coolkingsingh97** [comment]
![image](https://user-images.githubusercontent.com/14902241/207130768-bdea0785-8ed5-428b-8750-d54f0a4bbea1.png)

![image](https://user-images.githubusercontent.com/14902241/207130866-5c740fa0-91cb-404d-9446-f91ade779d71.png)
